require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GroupPostsController do

  # This should return the minimal set of attributes required to create a valid
  # GroupPost. As you add validations to GroupPost, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all group_posts as @group_posts" do
      group_post = GroupPost.create! valid_attributes
      get :index
      assigns(:group_posts).should eq([group_post])
    end
  end

  describe "GET show" do
    it "assigns the requested group_post as @group_post" do
      group_post = GroupPost.create! valid_attributes
      get :show, :id => group_post.id.to_s
      assigns(:group_post).should eq(group_post)
    end
  end

  describe "GET new" do
    it "assigns a new group_post as @group_post" do
      get :new
      assigns(:group_post).should be_a_new(GroupPost)
    end
  end

  describe "GET edit" do
    it "assigns the requested group_post as @group_post" do
      group_post = GroupPost.create! valid_attributes
      get :edit, :id => group_post.id.to_s
      assigns(:group_post).should eq(group_post)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GroupPost" do
        expect {
          post :create, :group_post => valid_attributes
        }.to change(GroupPost, :count).by(1)
      end

      it "assigns a newly created group_post as @group_post" do
        post :create, :group_post => valid_attributes
        assigns(:group_post).should be_a(GroupPost)
        assigns(:group_post).should be_persisted
      end

      it "redirects to the created group_post" do
        post :create, :group_post => valid_attributes
        response.should redirect_to(GroupPost.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved group_post as @group_post" do
        # Trigger the behavior that occurs when invalid params are submitted
        GroupPost.any_instance.stub(:save).and_return(false)
        post :create, :group_post => {}
        assigns(:group_post).should be_a_new(GroupPost)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GroupPost.any_instance.stub(:save).and_return(false)
        post :create, :group_post => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested group_post" do
        group_post = GroupPost.create! valid_attributes
        # Assuming there are no other group_posts in the database, this
        # specifies that the GroupPost created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GroupPost.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => group_post.id, :group_post => {'these' => 'params'}
      end

      it "assigns the requested group_post as @group_post" do
        group_post = GroupPost.create! valid_attributes
        put :update, :id => group_post.id, :group_post => valid_attributes
        assigns(:group_post).should eq(group_post)
      end

      it "redirects to the group_post" do
        group_post = GroupPost.create! valid_attributes
        put :update, :id => group_post.id, :group_post => valid_attributes
        response.should redirect_to(group_post)
      end
    end

    describe "with invalid params" do
      it "assigns the group_post as @group_post" do
        group_post = GroupPost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GroupPost.any_instance.stub(:save).and_return(false)
        put :update, :id => group_post.id.to_s, :group_post => {}
        assigns(:group_post).should eq(group_post)
      end

      it "re-renders the 'edit' template" do
        group_post = GroupPost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GroupPost.any_instance.stub(:save).and_return(false)
        put :update, :id => group_post.id.to_s, :group_post => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested group_post" do
      group_post = GroupPost.create! valid_attributes
      expect {
        delete :destroy, :id => group_post.id.to_s
      }.to change(GroupPost, :count).by(-1)
    end

    it "redirects to the group_posts list" do
      group_post = GroupPost.create! valid_attributes
      delete :destroy, :id => group_post.id.to_s
      response.should redirect_to(group_posts_url)
    end
  end

end
